parameters:
#    bwch_admin.example.class: Bwch\Bundle\AdminBundle\Example

services:
#    bwch_admin.example:
#        class: %bwch_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
